version: '3'

services:
  planka:
    image: {{ planka_image }}
    restart: on-failure
    volumes:
      - user-avatars:/app/public/user-avatars
      - project-background-images:/app/public/project-background-images
      - attachments:/app/private/attachments
    ports:
      - {{ planka_port }}:1337
    environment:
      - BASE_URL=https://{{ planka.base_url }}
      - DATABASE_URL=postgresql://postgres@postgres/planka
      - SECRET_KEY={{ key }}
      - OIDC_ISSUER={{ planka.oidcIssuer }}
      - OIDC_CLIENT_ID={{ planka.oidcClientID }}
      - OIDC_CLIENT_SECRET={{ planka.oidcClientSecret }}
      - OIDC_ENFORCED=true
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:14-alpine
    restart: on-failure
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=planka
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d planka"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  user-avatars:
  project-background-images:
  attachments:
  db-data: